name: snakedart
version: 0.3.0
author: Nane Kratzke <nane.kratzke@th-luebeck.de>
description: A Dart implementation of the famous Snake Game.
homepage: https://github.com/nkratzke/dartsnake

dev_dependencies:
  build_runner: ">=1.6.2 <2.0.0"
  build_web_compilers: ">=1.2.0 <3.0.0"

dependencies:
  http: ">=0.13.0 <1.0.0"

environment:
  sdk: '>=2.10.0 <3.0.0'
