name: snakedart
version: 0.2.0
author: Nane Kratzke <nane@nkode.io>
description: Dart implementation of the famous Snake Game.
homepage: https://github.com/nkratzke/dartsnake

dev_dependencies:
  build_runner: ">=1.6.2 <2.0.0"
  build_web_compilers: ">=1.2.0 <3.0.0"
